dist: xenial
jobs:
  fast_finish: true
  include:
  - name: PHP 7.2
    language: php
    php: 7.2
    services:
    - mysql
    addons:
      apt:
        packages:
        - nginx
        - realpath
      hosts:
      - vanilla.test
    install:
    - phpenv config-rm xdebug.ini
    - "./travis/install.sh"
    - cd vanilla
    before_script:
    - composer self-update
    - composer install --optimize-autoloader
    script:
    - "./vendor/bin/phpunit --exclude-group=large"
    yarn: true
  - name: JS Build & Test
    language: node_js
    install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
    - export PATH=$HOME/.yarn/bin:$PATH
    - "./travis/install.sh"
    - cd vanilla
    - yarn install --pure-lockfile
    node_js: lts/*
    addons:
      chrome: stable
    env:
    - TEST_FILE_ROOTS=()
    script:
    - yarn build -i
    - yarn test
cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$TRAVIS_BUILD_DIR/vanilla/node_modules"
  - "$TRAVIS_BUILD_DIR/vanilla/plugins/rich-editor/node_modules"
  yarn: true
env:
- VANILLA_BUILD_DISABLE_AUTO_BUILD=true
notifications:
  slack:
    secure: cOiTmT+HeK2SgNiEiOpB1j/bYWAmQZrnAuvTWYZdOZ/msTsncakqlU9Q7G4HwSmunxtVehVZ7ZvgSf+AolSpPOl2awePJqP7mZrtA0N2BGggj5VCd5l5gtAnG3WiZ+IBVB4iLmSzrlv0nzgXw9JPn/6hgcxc4z7KaY61YLw/nYSESOIPIpurmXMcnhBai7Bt7p8frEjn3rm0B7tq6egpdQcthL/DxWTu8xAWFmR8Kqjrd0qryzMxaQAp5BjFC/A+05uCva2xHpbbCaWWsknV7qG8N2k8155iPToP03fOt5qI3fbQPneR58GGrKiBYaEP17RBx9fbCTuaYMUjlm6knHr1euCLoiGYZ1zzl3F/+4qexu92rhdQZhvygQnTgJ5YfwU2Jx2J2R0P7J0BTqQvF1uO7BkCdEyrSmaeZcYV7qFrDn/xUqywCbAu66GAGImpPrgAOB2Oipi6YClDOt0vpE0eSvynMTbif7D6V4Eaj7EeVhm5MAHZddZsz34GHiD9FQI3CJzT4xNjmzCVIcUTag2SD4rY/iasy0JauFUdESODSm5pcAghoESje1vLj3UHem24jNxVxu5ogmAlPcdQNb4PtNuaqiSx2klG3pyZTTsWPDdO2fqSdbwanp6fNNZd/Cg0hdTB4BNf6YSO+Cvg3wwRpvmpSpxDrxzQzb1iEt0=
