dist: xenial
jobs:
  fast_finish: true
  include:
  - name: PHP 7.2
    language: php
    php: 7.2
    services:
    - mysql
    addons:
      apt:
        packages:
        - nginx
        - realpath
      hosts:
      - vanilla.test
    before_script:
    - composer self-update
    - composer install --optimize-autoloader
    script:
    - "./vendor/bin/phpunit --exclude-group=large"
    yarn: true
  - name: JS Build & Test
    language: node_js
    node_js: 10.9
    addons:
      chrome: stable
    env:
    - TEST_FILE_ROOTS=()
    script:
    - yarn build -i
    - yarn test
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
- phpenv config-rm xdebug.ini
- "./travis/install.sh"
- cd vanilla
- yarn install --pure-lockfile
cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$TRAVIS_BUILD_DIR/vanilla/node_modules"
  - "$TRAVIS_BUILD_DIR/vanilla/plugins/rich-editor/node_modules"
  yarn: true
env:
- VANILLA_BUILD_DISABLE_AUTO_BUILD=true
notifications:
  slack:
    secure: YYlyi4RfI4ky8NRUgPzPEwVn4GE6uVNe9KohoQGgPJQ+TN6hDGJoWKrVqcMBiG+oe/FyIMFMZGCVoIYuDEQjd5Z8lzNLjSSpg2xoVs6qFmUGt72dtNw8eUiammlQDvlCqk0KSt8iD/jmnA/wVpwD2uz+77yUAQJpgEmofKQ1F4I=
